# Generated by Django 2.1 on 2020-08-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_time', models.DateField(auto_now_add=True)),
                ('ip_addr', models.GenericIPAddressField(verbose_name='评论者的IP')),
            ],
            options={
                'verbose_name': '评论信息',
                'db_table': 'commentinfo',
                'ordering': ['-comment_time'],
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(default='book.jpg', upload_to='book_images', verbose_name='书籍封面')),
                ('book_name', models.CharField(max_length=20, verbose_name='书籍名称')),
                ('book_url', models.CharField(max_length=50, verbose_name='书籍链接')),
                ('description', models.TextField(verbose_name='书籍描述')),
                ('book_author', models.CharField(max_length=10, null=True, verbose_name='书籍作者')),
                ('book_type', models.SmallIntegerField(choices=[(0, '编程类'), (1, '其他类')], default=0, verbose_name='书籍类型')),
                ('book_pub', models.CharField(max_length=30, null=True, verbose_name='书籍出版社')),
                ('book_pubdate', models.DateField(null=True, verbose_name='书籍出版日期')),
                ('book_adddate', models.DateField(auto_now_add=True, verbose_name='书籍添加日期')),
                ('book_likes', models.IntegerField(default=0, verbose_name='书籍点赞量')),
                ('commentcount', models.IntegerField(default=0, verbose_name='书籍评论量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '书籍信息',
                'db_table': 'bookinfo',
                'ordering': ['-book_adddate'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('head_image', models.ImageField(default='head_image.jpg', upload_to='user_images')),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='用户性别')),
                ('email', models.CharField(max_length=30, verbose_name='用户邮箱')),
                ('phonenum', models.CharField(max_length=15, null=True, verbose_name='用户电话')),
                ('grade', models.SmallIntegerField(choices=[(0, 'VIP'), (1, 'SVIP'), (2, 'SSVIP')], default=0, verbose_name='用户等级')),
                ('user_addtime', models.DateField(auto_now_add=True, verbose_name='用户创建时间')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'userinfo',
                'ordering': ['-user_addtime'],
            },
        ),
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='书籍名称')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '人物信息',
                'db_table': 'userbookinfo',
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
    ]
