# Generated by Django 2.1 on 2020-08-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200823_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
